### ISSUE TITLE
Adding Small and Grand Charms to droplist

### ISSUE THREAD

**Issue by Epi1234** [dschu012/d2lootfilter#1]
Hello and thanks a bunch for your awesome lootfilter!

I got a couple of questions:

1. Are you planning any further releases for this software? If so, do you have a rough estimate on when?
2. Could you tell me how I can add Small and Grand Charms to the visibility/droplist of items that get displayed? In the Item.finder file it says "show Grand Charms" etc..., but I didn't find any charms after around 100 LK runs which seems fishy to say the least.
3. Could you tell me the same as in #2 but for flawless amethysts and topazes?

Cheers and take care :)

**Comment by ShadwDrgn** [comment]
Hey @Epi1234 ! It's me again. If you look at the sample item.filter it includes sections to show grand/small charms. Hopefully that solves your problem.
