### ISSUE TITLE
Description not showing.

### ISSUE THREAD

**Issue by ShadwDrgn** [dschu012/d2lootfilter#10]
[Veronica.zip](https://github.com/dschu012/d2lootfilter/files/7148937/Veronica.zip)

![d2l-nodescription](https://user-images.githubusercontent.com/2470781/132971011-83b07b65-bbbf-4c80-9f6c-99849ec030dd.png)

**Comment by ShadwDrgn** [comment]
Description is in the debug but not on the item. Other socketed (4 socket) dusk shrouds i have also do this. not sure if other armors as well. line 313 is the line that adds the description. from the latest item.filter file

**Comment by dschu012** [comment]
Cool. I'll try to take a look this week.

**Comment by dschu012** [comment]
@ShadwDrgn think this should be fixed in latest. v0.5
