### ISSUE TITLE
Sub-Gem class not working as expected

### ISSUE THREAD

**Issue by RedDVal** [dschu012/d2lootfilter#11]
Existing (but not working):
Show
    Class Gem
    Class Chipped Gem, Flawed Gem, Standard Gem
    CharacterLevel <= 50

Working (but not intuitive)
Show
    Class Gem
    Class Chipped, Flawed, Standard
    CharacterLevel <= 50

We should either update item.filter and class.md with "Chipped" instead of "Chipped Gem"
Or
Update code to correctly match "Class Chipped Gem"

**Comment by RedDVal** [comment]
Also, do a ctrl+h for Gray to replace with Grey, there were over 10 hits on 0.2.

**Comment by dschu012** [comment]
ideally the fix is the 2nd. "Chipped Gem" should be the one I want to work so it matches https://github.com/fabd/diablo2/blob/master/code/d2_113_data/ItemTypes.txt#L94. ill see if i can take a look at some of these issues this week.

**Comment by dschu012** [comment]
Closing issue. Reopen if it is still an issue on the latest.
