### ISSUE TITLE
Matching potions by ID doesn't work

### ISSUE THREAD

**Issue by RedDVal** [dschu012/d2lootfilter#12]
Show
    Code hp3, mp3

Doesn't seem to do anything.
Tested on 0.2.

**Comment by ShadwDrgn** [comment]
Code filter in general  seems to have some bugs. I wasn't able to get essences working with Code either.

**Comment by dschu012** [comment]
Almost seems like it's misc.txt items. On the list of things I hope to look at this week.

**Comment by dschu012** [comment]
@RedDVal this should work in the latest release. 0.4 https://github.com/dschu012/d2lootfilter/releases

**Comment by dschu012** [comment]
Closing issue. Reopen if it is still an issue on the latest.
