### ISSUE TITLE
setbordercolor seems to not work

### ISSUE THREAD

**Issue by ShadwDrgn** [dschu012/d2lootfilter#14]
at the top of my item.filter:
```
Show
    SetBorderColor Red
Hide
```
![2021-09-14 11_24_35-Diablo II DX  1680x720, scale 200%](https://user-images.githubusercontent.com/2470781/133286813-a9f55391-bc77-484e-bb76-66101f5de641.png)
[Veronica.zip](https://github.com/dschu012/d2lootfilter/files/7163171/Veronica.zip)

D2 Version: 1.14d
D2L Version: The one you sent me today on discord. I assume 0.4

**Comment by dschu012** [comment]
Updated 0.4 with a newer dll. https://github.com/dschu012/d2lootfilter/releases/tag/v0.4-alpha "should" fix it.

**Comment by dschu012** [comment]
Closing issue. Reopen if it is still an issue on the latest.
