### ISSUE TITLE
SetName Color options not working in .4?

### ISSUE THREAD

**Issue by BinaryNebula** [dschu012/d2lootfilter#15]
First I just wanted to say fantastic loot filter and thanks for making it compatible with 1.14d, seems to be the only filter available with compatibility. I am currently modifying the example filter to better suit me and having issues with the item.filter config coloring the {Name} parameter.

For instance the default filter has:

Show
	Rune in El-Fal
        SetName {Orange}{Name}

But all my runes are displaying with white names.
![image](https://user-images.githubusercontent.com/43211969/133323808-aea14b76-be1b-496b-952a-4af73847a8ca.png)

If I add characters between Orange and Name it will properly change those characters.
![image](https://user-images.githubusercontent.com/43211969/133323987-1271acd1-4f09-4e8e-a89a-4af009b1c98f.png)

Not sure if this is an issue with my syntax, the filter file, or something different in .4?

**Comment by dschu012** [comment]
I imagine it has to do with

```
Show
    Rarity < Magic
    SetName {White}{Name}
Continue
```

setting the name to be white. the best way to try to debug issue like this is to type `/debug` into chat for most details. It'll tell you what rules were applied to an item.

**Comment by BinaryNebula** [comment]
Ah fantastic good to know. Thank for the fast response looks good now.
