### ISSUE TITLE
Bug report: Crash when restatting character

### ISSUE THREAD

**Issue by Epi1234** [dschu012/d2lootfilter#2]
In case you plan to update the lootfilter, here's a bug report.

When you try to restat a character using the plugy restatting feature ingame, the game instantly crashes.

**Comment by ShadwDrgn** [comment]
Didn't notice this, but yeah. my game also crashes viewing charscreen :~( so +1 here

**Comment by dschu012** [comment]
https://github.com/dschu012/d2lootfilter/releases/tag/v0.2-alpha latest alpha should fix the crash
