### ISSUE TITLE
Highrunes aren't showing up in the vanilla item.filter droplist?!

### ISSUE THREAD

**Issue by Epi1234** [dschu012/d2lootfilter#3]
So I've done about 200 LK runs and haven't found a single rune with the lootfinder. So in order to test the drop getting displayed, I dropped both a Gul and a Vex rune from my stash and they weren't displayed.

Does that mean that High Runes aren't being displayed in the vanilla lootfilter? That would be extremely bad...

**Comment by ShadwDrgn** [comment]
Just a heads up, if you're using thee included item.filter you should instead consider using the one from the docs that's referred to as a sample filter. That filter includes lines that show runes.
