### ISSUE TITLE
Stuff gets destroyed

### ISSUE THREAD

**Issue by sharpwg1337** [dschu012/d2lootfilter#38]
I dropped two stashed items (random armors with sockets) and both got seemingly deleted/destroyed. This was SP of course so I reverted to my backup save, disabled this plugin and did it again. Did not get destroyed. Not sure why this mod did that.

**Comment by dschu012** [comment]
Your filter is setup such that it is hiding those items, which is why you think they are destroyed.

**Comment by sharpwg1337** [comment]
> Your filter is setup such that it is hiding those items, which is why you think they are destroyed.

Certainly makes sense to me, I am using the default one that comes with the release. Would you happen to know which specific lines hide things. I would prefer to hide nothing.

**Comment by dschu012** [comment]
Likely the `Hide` at the very end of the `item.filter.` But you can type in `/debug` and hover the item in your inventory to see the line responsible for hiding the item. It would be the last `Matched Line`
