### ISSUE TITLE
potions

### ISSUE THREAD

**Issue by ShadwDrgn** [dschu012/d2lootfilter#4]
is there a way to make all potions show up or potions >= 4 without having like:
Show
    Code hp4
Show
    Code hp5
 for both mana and health pots? perhaps with one line like
Show
    potion >= 4
??

**Comment by dschu012** [comment]
Currently no easy way to do something similar to that.

**Comment by ShadwDrgn** [comment]
i just turned on all Class potion and i'm fine with it for the time being.
