### ISSUE TITLE
flawless gem, perfect gem not showing

### ISSUE THREAD

**Issue by ShadwDrgn** [dschu012/d2lootfilter#5]
```
#always show flawless/perf gems
Show
    Class Gem
    Class Flawless Gem, Perfect Gem
```

The above code in your sample filter does not seem to work. I've tried removing the first part "Class Gem" and tried removing also perfect gem so there would be no comma but none of it makes the item show.

Please note this likely affects more than this entry (like the chipped gems entry maybe.) also unlike when invalid entries normally causee the game not to load at all, the game DOES load with this entry it just seems to completely ignore it.

This is pretty concerning because who knows what else it's hiding (like the gems) that it says it's showing :~(

**Comment by ShadwDrgn** [comment]
my paste is missing the indent but it's there in the file. sorry

**Comment by dschu012** [comment]
"Also btw i did notice one more thing. sometimes items that show are claiming in debug they match the last hide line, but clearly they don't hide."


Provide concrete examples if you can. Also if you have a save (d2s) file with the items in question (the flawless gems in this instance) it'll make my life easier when I get back around to this project.

**Comment by ShadwDrgn** [comment]
not sure how i didn't think of that. I'll try to find out what I was looking at that was causing this. hopefully it's somehow connected to my stupidity with the other issue i already closed. and i'll be able to just close this one too leaving ONLY the charscreen crash issue. If you have a suggestion on how i could get you a stacktrace or error log for that crash i'll be happy to try to set it up. :D

**Comment by dschu012** [comment]
honestly easier if i just look at it. i'll try to make time earlier since that bug is kind of a showstopper.

**Comment by dschu012** [comment]
@ShadwDrgn https://github.com/dschu012/d2lootfilter/releases/tag/v0.2-alpha see if this fixes the crash for you.

**Comment by ShadwDrgn** [comment]
Wow thanks for looking at this so quickly!!! Sadly, though, the game doesn't even launch with this one at all. Switching back to v0.1 gets it launching again, and I tried running from command line to see if there's a crash or stdout log or something but no such luck. It immediately goes back to command line:
```
C:\Program Files (x86)\Diablo II>"C:\Program Files (x86)\Diablo II\Game.exe" -3dfx

C:\Program Files (x86)\Diablo II>
```

**Comment by Karyoplasma** [comment]
> https://github.com/dschu012/d2lootfilter/releases/tag/v0.2-alpha see if this fixes the crash for you.

Haven't had a crash with this one so far. No extensive testing done tho, only a couple runs and tries.

**Comment by ShadwDrgn** [comment]
this works in the newest filter and version. just tested

**Comment by RedDVal** [comment]
@ShadwDrgn The fix for me was:
Show
    Class Gem
    Class Flawless, Perfect

I opened a new issue to address this.
