### ISSUE TITLE
Request: Already own

### ISSUE THREAD

**Issue by ShadwDrgn** [dschu012/d2lootfilter#8]
It would be amazing if i could put something on a section that makes it so if i already have an item in my stash that matches the filter it matches.

like
```
Show
    Rarity Unique, Set
    OwnedType >= 1
    SetDescription {description} (OWNED ALREADY)
Continue
```

This would be AWESOME for grail collectors and would of course also be ideal if it could work even with plugy infinite stash and shared stash (not sure how this works/would work)

Of course this becomes complicated when it comes to unid vs id. This is why i called it "OwnedType" so it could match based on the item type + your filter (in this case unique and sets only)

**Comment by dschu012** [comment]
I'm not sure if you have access to your stash items when you are out of town, so that might kind of kill that feature. But I can try to take a look at it.

**Comment by ShadwDrgn** [comment]
Looks like the game knows how many of the rest of Arcanna's I have while I just hold the staff in my inventory. I'm in river of flames so I assume there must be some level of access. I do know the game has code to prevent you from opening the stash from outside town, but it probably does have access somewhere in the code somehow.

**Comment by dschu012** [comment]
this seems like it kinda works in 0.4 https://github.com/dschu012/d2lootfilter/releases

one issue I see w/ this right now is when you join a game and have two of the same item in your inventory, when we run the rules on the first item the second item does not yet exist in the game so it won't match that rule. this is the rule I was using

```
Show
    SetName {Red}Already Owned {Name}
Continue
```

![image](https://user-images.githubusercontent.com/1458109/133264679-49f2580f-c468-4105-b7b3-d795b8d0c7a5.png)

**Comment by dschu012** [comment]
after more testing i'm seeing weird stuff so probably not ready for real use yet.

**Comment by dschu012** [comment]
Closing issue. Reopen if it is still an issue on the latest.
